;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        color-rg-apply-changed
        color-rg-beginning-of-line
        color-rg-switch-to-edit-mode
        hungry-delete-backward
        hungry-delete-forward
        org-end-of-line
        org-metaright
        org-self-insert-command
        org-shiftright
        org-yank
        sp-backward-delete-char
        sp-delete-char
        sp-kill-word
        sp-unwrap-sexp
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ivy-alt-done
        ))
