;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hungry-delete-backward
        hungry-delete-forward
        org-metaright
        org-self-insert-command
        org-shiftright
        sp-backward-delete-char
        sp-delete-char
        sp-kill-word
        sp-unwrap-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ivy-alt-done
        ))
